version: '3'

services:
  ctrl-db:
    container_name: livemix-ctrl-db
    hostname: "postgres"
    image: "postgres:15"
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  memcached:
    container_name: livemix-ctrl-memcached
    hostname: memcached
    image: memcached:1.6.20-alpine
    ports:
      - 127.0.0.1:18080:18080
    expose:
      - 8080
    command:
      - -m
      - '256'
      - -I
      - 10m
      - -p
      - '18080'
