version: '3'

services:
  ctrl-db:
    container_name: livemix-ctrl-db
    restart: always
    hostname: "postgres"
    image: "postgres:15"
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  memcached:
    container_name: livemix-ctrl-memcached
    restart: always
    hostname: memcached
    image: memcached:1.6.20-alpine
    ports:
      - 127.0.0.1:18080:18080
    expose:
      - 8080
    command:
      - -m
      - '256'
      - -I
      - 10m
      - -p
      - '18080'

  minio:
    container_name: livemix-ctrl-minio
    restart: always
    hostname: minio
    image: quay.io/minio/minio:RELEASE.2023-07-07T07-13-57Z
    command:
      - server
      - /data
      - --console-address
      - ":9090"
    environment:
      LOG_LEVEL: info
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    expose:
      - 9000
      - 9090
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9090:9090
